/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_JNI_JNIMethods */

#ifndef _Included_org_apache_spark_JNI_JNIMethods
#define _Included_org_apache_spark_JNI_JNIMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_JNI_JNIMethods
 * Method:    nativeMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_JNI_JNIMethods_nativeMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_apache_spark_JNI_JNIMethods
 * Method:    returnInternalRow
 * Signature: (Lorg/apache/spark/sql/catalyst/InternalRow;)Lorg/apache/spark/sql/catalyst/InternalRow;
 */
JNIEXPORT jobject JNICALL Java_org_apache_spark_JNI_JNIMethods_returnInternalRow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_spark_JNI_JNIMethods
 * Method:    returnUnsafeRow
 * Signature: (Lorg/apache/spark/sql/catalyst/expressions/UnsafeRow;)Lorg/apache/spark/sql/catalyst/expressions/UnsafeRow;
 */
JNIEXPORT jobject JNICALL Java_org_apache_spark_JNI_JNIMethods_returnUnsafeRow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_spark_JNI_JNIMethods
 * Method:    JNICompareDouble
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_JNI_JNIMethods_JNICompareDouble
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_apache_spark_JNI_JNIMethods
 * Method:    JNIOneapiCompareGreaterFloatArray
 * Signature: ([FFII)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_org_apache_spark_JNI_JNIMethods_JNIOneapiCompareGreaterFloatArray
  (JNIEnv *, jobject, jfloatArray, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
