/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_jni_NativeHelloWorld */

#ifndef _Included_org_apache_spark_jni_NativeHelloWorld
#define _Included_org_apache_spark_jni_NativeHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_jni_NativeHelloWorld
 * Method:    nativeMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_spark_jni_NativeHelloWorld_nativeMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
